name: Rapid7 InsightAppSec Scan
uses: rapid7/insightappsec-scan-github-actions@v1.3.0
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: rapid7/insightappsec-scan-github-actions@v1.1.0
        with:
          region: "eu"
          api-key: ${{ secrets.IAS_API_KEY }}
          scan-config-id: "9f87982a-7e61-4eeb-8665-708af8b66d0c"
          vuln-query: "vulnerability.severity = 'MEDIUM'"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
