name: IAS WebScan Test
on:
  push:
    branches: main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: rapid7/insightappsec-scan-github-actions@v1.3.0
        with:
          region: "eu"
          api-key: d3a93707-dab1-4932-ae80-5d9831cce008
          scan-config-id: "8aae26cb-670c-4553-b87f-c7a3d4008e1a"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
